@BusinessSolutionChatGpt.Api_HostAddress = http://localhost:5110

POST {{BusinessSolutionChatGpt.Api_HostAddress}}/api/cart/
Accept: application/json

GET {{BusinessSolutionChatGpt.Api_HostAddress}}/api/cart/
Accept: application/json

GET {{BusinessSolutionChatGpt.Api_HostAddress}}/api/cart/total
Accept: application/json

DELETE {{BusinessSolutionChatGpt.Api_HostAddress}}/api/cart/{id}
Accept: application/json

DELETE {{BusinessSolutionChatGpt.Api_HostAddress}}/api/cart/
Accept: application/json

###
