//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSolutionChatGpt.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessSolutionChatGpt.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Naciśnij 1 aby rozpocząć dodawanie produktu do koszyka.
        /// </summary>
        internal static string AddProductInstruction {
            get {
                return ResourceManager.GetString("AddProductInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Identyfikator produktu jest pusty.
        /// </summary>
        internal static string ProductEmptyIdentifierValidationMessage {
            get {
                return ResourceManager.GetString("ProductEmptyIdentifierValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa jest pusta.
        /// </summary>
        internal static string ProductEmptyNameValidationMessage {
            get {
                return ResourceManager.GetString("ProductEmptyNameValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cena jest pusta.
        /// </summary>
        internal static string ProductEmptyPriceValidationMessage {
            get {
                return ResourceManager.GetString("ProductEmptyPriceValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podaj identyfikator produktu.
        /// </summary>
        internal static string ProductIdentifierInstruction {
            get {
                return ResourceManager.GetString("ProductIdentifierInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Identyfikator produktu nie został podany.
        /// </summary>
        internal static string ProductMissingIdentifierValidationMessage {
            get {
                return ResourceManager.GetString("ProductMissingIdentifierValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa została nie podana.
        /// </summary>
        internal static string ProductMissingNameValidationMessage {
            get {
                return ResourceManager.GetString("ProductMissingNameValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cena nie została podana.
        /// </summary>
        internal static string ProductMissingPriceValidationMessage {
            get {
                return ResourceManager.GetString("ProductMissingPriceValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podaj nazwę produktu.
        /// </summary>
        internal static string ProductNameInstruction {
            get {
                return ResourceManager.GetString("ProductNameInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ciąg znaków to nie cena.
        /// </summary>
        internal static string ProductNotDecimalPriceValidationMessage {
            get {
                return ResourceManager.GetString("ProductNotDecimalPriceValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Produkt nie istnieje.
        /// </summary>
        internal static string ProductNotExistValidationMessage {
            get {
                return ResourceManager.GetString("ProductNotExistValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Niepoprawny identyfikator produktu.
        /// </summary>
        internal static string ProductNotIntegerIdentifierValidationMessage {
            get {
                return ResourceManager.GetString("ProductNotIntegerIdentifierValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cena musi być większa od 0.
        /// </summary>
        internal static string ProductNotPositivePriceValidationMessage {
            get {
                return ResourceManager.GetString("ProductNotPositivePriceValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podaj cenę produktu.
        /// </summary>
        internal static string ProductPriceInstruction {
            get {
                return ResourceManager.GetString("ProductPriceInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Naciśnij 5 aby usunąć wszystkie książki.
        /// </summary>
        internal static string RemoveAllProductsInstruction {
            get {
                return ResourceManager.GetString("RemoveAllProductsInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Naciśnij 4 aby usnąć konkretny produkt.
        /// </summary>
        internal static string RemoveSpecifiedProductInstruction {
            get {
                return ResourceManager.GetString("RemoveSpecifiedProductInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Naciśnij 2 aby rozpocząć wyświetlić wszystkie produkty w koszyku.
        /// </summary>
        internal static string ShowAllProductsInstruction {
            get {
                return ResourceManager.GetString("ShowAllProductsInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Naciśnij 3 aby rozpocząć zobaczyć ile masz do zapłacenia.
        /// </summary>
        internal static string ShowTotalCostInstruction {
            get {
                return ResourceManager.GetString("ShowTotalCostInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Naciśnij Esc aby zakończyć pracę.
        /// </summary>
        internal static string StopShopAppInstruction {
            get {
                return ResourceManager.GetString("StopShopAppInstruction", resourceCulture);
            }
        }
    }
}
